---
- hosts: pi
  remote_user: pi
  vars_files:
    - vars/main.yml
  tasks:
    - import_tasks: tasks/config-backup.yml
      tags: config

    # - import_tasks: tasks/apt-updates.yml
    #   when: update_apt_packages
    #   tags: update
